package com.example.modelo;

// default package
// Generated 29/09/2014 10:20:51 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Auditoria generated by hbm2java
 */
public class Auditoria implements java.io.Serializable {

	private long id;
	private Usuario usuario;
	private Date fecha;
	private String accion;
	private String modelo;
	private String campo;
	private String campoNuevoValor;

	public Auditoria() {
	}

	public Auditoria(long id, Usuario usuario) {
		this.id = id;
		this.usuario = usuario;
	}

	public Auditoria(long id, Usuario usuario, Date fecha, String accion,
			String modelo, String campo, String campoNuevoValor) {
		this.id = id;
		this.usuario = usuario;
		this.fecha = fecha;
		this.accion = accion;
		this.modelo = modelo;
		this.campo = campo;
		this.campoNuevoValor = campoNuevoValor;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getAccion() {
		return this.accion;
	}

	public void setAccion(String accion) {
		this.accion = accion;
	}

	public String getModelo() {
		return this.modelo;
	}

	public void setModelo(String modelo) {
		this.modelo = modelo;
	}

	public String getCampo() {
		return this.campo;
	}

	public void setCampo(String campo) {
		this.campo = campo;
	}

	public String getCampoNuevoValor() {
		return this.campoNuevoValor;
	}

	public void setCampoNuevoValor(String campoNuevoValor) {
		this.campoNuevoValor = campoNuevoValor;
	}

}
