package com.example.modelo;

// default package
// Generated 29/09/2014 10:20:51 PM by Hibernate Tools 4.0.0

/**
 * CalificacionSitio generated by hbm2java
 */
public class CalificacionSitio implements java.io.Serializable {

	private long id;
	private Sitio sitio;
	private Usuario usuario;
	private int calificacion;

	public CalificacionSitio() {
	}

	public CalificacionSitio(long id, Sitio sitio, Usuario usuario,
			int calificacion) {
		this.id = id;
		this.sitio = sitio;
		this.usuario = usuario;
		this.calificacion = calificacion;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Sitio getSitio() {
		return this.sitio;
	}

	public void setSitio(Sitio sitio) {
		this.sitio = sitio;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public int getCalificacion() {
		return this.calificacion;
	}

	public void setCalificacion(int calificacion) {
		this.calificacion = calificacion;
	}

}
