package com.example.modelo;

// default package
// Generated 29/09/2014 10:20:51 PM by Hibernate Tools 4.0.0

/**
 * CalificacionRutaTuristica generated by hbm2java
 */
public class CalificacionRutaTuristica implements java.io.Serializable {

	private long id;
	private RutaTuristica rutaTuristica;
	private Usuario usuario;
	private Integer calificacion;

	public CalificacionRutaTuristica() {
	}

	public CalificacionRutaTuristica(long id, RutaTuristica rutaTuristica,
			Usuario usuario) {
		this.id = id;
		this.rutaTuristica = rutaTuristica;
		this.usuario = usuario;
	}

	public CalificacionRutaTuristica(long id, RutaTuristica rutaTuristica,
			Usuario usuario, Integer calificacion) {
		this.id = id;
		this.rutaTuristica = rutaTuristica;
		this.usuario = usuario;
		this.calificacion = calificacion;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public RutaTuristica getRutaTuristica() {
		return this.rutaTuristica;
	}

	public void setRutaTuristica(RutaTuristica rutaTuristica) {
		this.rutaTuristica = rutaTuristica;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Integer getCalificacion() {
		return this.calificacion;
	}

	public void setCalificacion(Integer calificacion) {
		this.calificacion = calificacion;
	}

}
