package com.example.modelo;

// default package
// Generated 29/09/2014 10:20:51 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Checkin generated by hbm2java
 */
public class Checkin implements java.io.Serializable {

	private long id;
	private Evento evento;
	private Sitio sitio;
	private Usuario usuario;
	private Date fecha;

	public Checkin() {
	}

	public Checkin(long id, Usuario usuario, Date fecha) {
		this.id = id;
		this.usuario = usuario;
		this.fecha = fecha;
	}

	public Checkin(long id, Evento evento, Sitio sitio, Usuario usuario,
			Date fecha) {
		this.id = id;
		this.evento = evento;
		this.sitio = sitio;
		this.usuario = usuario;
		this.fecha = fecha;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Evento getEvento() {
		return this.evento;
	}

	public void setEvento(Evento evento) {
		this.evento = evento;
	}

	public Sitio getSitio() {
		return this.sitio;
	}

	public void setSitio(Sitio sitio) {
		this.sitio = sitio;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

}
