package com.example.modelo;

// default package
// Generated 29/09/2014 10:20:51 PM by Hibernate Tools 4.0.0

/**
 * ComentarioSitio generated by hbm2java
 */
public class ComentarioSitio implements java.io.Serializable {

	private long id;
	private Sitio sitio;
	private Usuario usuario;
	private String comentario;

	public ComentarioSitio() {
	}

	public ComentarioSitio(long id, Sitio sitio, Usuario usuario) {
		this.id = id;
		this.sitio = sitio;
		this.usuario = usuario;
	}

	public ComentarioSitio(long id, Sitio sitio, Usuario usuario,
			String comentario) {
		this.id = id;
		this.sitio = sitio;
		this.usuario = usuario;
		this.comentario = comentario;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Sitio getSitio() {
		return this.sitio;
	}

	public void setSitio(Sitio sitio) {
		this.sitio = sitio;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

}
