package com.example.modelo;

// default package
// Generated 29/09/2014 10:20:51 PM by Hibernate Tools 4.0.0

/**
 * EventoCategoriaEvento generated by hbm2java
 */
public class EventoCategoriaEvento implements java.io.Serializable {

	private long id;
	private Evento evento;
	private CategoriaEvento categoriaEvento;

	public EventoCategoriaEvento() {
	}

	public EventoCategoriaEvento(long id, Evento evento,
			CategoriaEvento categoriaEvento) {
		this.id = id;
		this.evento = evento;
		this.categoriaEvento = categoriaEvento;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Evento getEvento() {
		return this.evento;
	}

	public void setEvento(Evento evento) {
		this.evento = evento;
	}

	public CategoriaEvento getCategoriaEvento() {
		return this.categoriaEvento;
	}

	public void setCategoriaEvento(CategoriaEvento categoriaEvento) {
		this.categoriaEvento = categoriaEvento;
	}

}
