package com.example.modelo;

// default package
// Generated 29/09/2014 10:20:51 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Evento generated by hbm2java
 */
public class Evento implements java.io.Serializable {

	private long id;
	private Usuario usuario;
	private String nombre;
	private String descripcion;
	private String lugar;
	private String latitud;
	private String longitud;
	private Integer habilitado;
	private Date fecha;
	private Date validez;
	private Date hora;
	private Set eventoCategoriaEventos = new HashSet(0);
	private Set fotos = new HashSet(0);
	private Set checkins = new HashSet(0);
	private Set dias = new HashSet(0);

	public Evento() {
	}

	public Evento(long id, Usuario usuario) {
		this.id = id;
		this.usuario = usuario;
	}

	public Evento(long id, Usuario usuario, String nombre, String descripcion,
			String lugar, String latitud, String longitud, Integer habilitado,
			Date fecha, Date validez, Date hora, Set eventoCategoriaEventos,
			Set fotos, Set checkins, Set dias) {
		this.id = id;
		this.usuario = usuario;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.lugar = lugar;
		this.latitud = latitud;
		this.longitud = longitud;
		this.habilitado = habilitado;
		this.fecha = fecha;
		this.validez = validez;
		this.hora = hora;
		this.eventoCategoriaEventos = eventoCategoriaEventos;
		this.fotos = fotos;
		this.checkins = checkins;
		this.dias = dias;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getLugar() {
		return this.lugar;
	}

	public void setLugar(String lugar) {
		this.lugar = lugar;
	}

	public String getLatitud() {
		return this.latitud;
	}

	public void setLatitud(String latitud) {
		this.latitud = latitud;
	}

	public String getLongitud() {
		return this.longitud;
	}

	public void setLongitud(String longitud) {
		this.longitud = longitud;
	}

	public Integer getHabilitado() {
		return this.habilitado;
	}

	public void setHabilitado(Integer habilitado) {
		this.habilitado = habilitado;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Date getValidez() {
		return this.validez;
	}

	public void setValidez(Date validez) {
		this.validez = validez;
	}

	public Date getHora() {
		return this.hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

	public Set getEventoCategoriaEventos() {
		return this.eventoCategoriaEventos;
	}

	public void setEventoCategoriaEventos(Set eventoCategoriaEventos) {
		this.eventoCategoriaEventos = eventoCategoriaEventos;
	}

	public Set getFotos() {
		return this.fotos;
	}

	public void setFotos(Set fotos) {
		this.fotos = fotos;
	}

	public Set getCheckins() {
		return this.checkins;
	}

	public void setCheckins(Set checkins) {
		this.checkins = checkins;
	}

	public Set getDias() {
		return this.dias;
	}

	public void setDias(Set dias) {
		this.dias = dias;
	}

}
