package com.example.modelo;

// default package
// Generated 29/09/2014 10:20:51 PM by Hibernate Tools 4.0.0

/**
 * Foto generated by hbm2java
 */
public class Foto implements java.io.Serializable {

	private long id;
	private RutaTuristica rutaTuristica;
	private Evento evento;
	private Promocion promocion;
	private Sitio sitio;
	private byte[] imagen;

	public Foto() {
	}

	public Foto(long id, byte[] imagen) {
		this.id = id;
		this.imagen = imagen;
	}

	public Foto(long id, RutaTuristica rutaTuristica, Evento evento,
			Promocion promocion, Sitio sitio, byte[] imagen) {
		this.id = id;
		this.rutaTuristica = rutaTuristica;
		this.evento = evento;
		this.promocion = promocion;
		this.sitio = sitio;
		this.imagen = imagen;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public RutaTuristica getRutaTuristica() {
		return this.rutaTuristica;
	}

	public void setRutaTuristica(RutaTuristica rutaTuristica) {
		this.rutaTuristica = rutaTuristica;
	}

	public Evento getEvento() {
		return this.evento;
	}

	public void setEvento(Evento evento) {
		this.evento = evento;
	}

	public Promocion getPromocion() {
		return this.promocion;
	}

	public void setPromocion(Promocion promocion) {
		this.promocion = promocion;
	}

	public Sitio getSitio() {
		return this.sitio;
	}

	public void setSitio(Sitio sitio) {
		this.sitio = sitio;
	}

	public byte[] getImagen() {
		return this.imagen;
	}

	public void setImagen(byte[] imagen) {
		this.imagen = imagen;
	}

}
