package com.example.modelo;

// default package
// Generated 29/09/2014 10:20:51 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Promocion generated by hbm2java
 */
public class Promocion implements java.io.Serializable {

	private long id;
	private Sitio sitio;
	private Date validez;
	private String descripcion;
	private String nombre;
	private Set fotos = new HashSet(0);

	public Promocion() {
	}

	public Promocion(long id, Sitio sitio) {
		this.id = id;
		this.sitio = sitio;
	}

	public Promocion(long id, Sitio sitio, Date validez, String descripcion,
			String nombre, Set fotos) {
		this.id = id;
		this.sitio = sitio;
		this.validez = validez;
		this.descripcion = descripcion;
		this.nombre = nombre;
		this.fotos = fotos;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Sitio getSitio() {
		return this.sitio;
	}

	public void setSitio(Sitio sitio) {
		this.sitio = sitio;
	}

	public Date getValidez() {
		return this.validez;
	}

	public void setValidez(Date validez) {
		this.validez = validez;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getFotos() {
		return this.fotos;
	}

	public void setFotos(Set fotos) {
		this.fotos = fotos;
	}

}
