package com.example.modelo;

// default package
// Generated 29/09/2014 10:20:51 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * RolUsuario generated by hbm2java
 */
public class RolUsuario implements java.io.Serializable {

	private long id;
	private String rol;
	private Set rolUsuarioUsuarios = new HashSet(0);

	public RolUsuario() {
	}

	public RolUsuario(long id) {
		this.id = id;
	}

	public RolUsuario(long id, String rol, Set rolUsuarioUsuarios) {
		this.id = id;
		this.rol = rol;
		this.rolUsuarioUsuarios = rolUsuarioUsuarios;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getRol() {
		return this.rol;
	}

	public void setRol(String rol) {
		this.rol = rol;
	}

	public Set getRolUsuarioUsuarios() {
		return this.rolUsuarioUsuarios;
	}

	public void setRolUsuarioUsuarios(Set rolUsuarioUsuarios) {
		this.rolUsuarioUsuarios = rolUsuarioUsuarios;
	}

}
