package com.example.modelo;

// default package
// Generated 29/09/2014 10:20:51 PM by Hibernate Tools 4.0.0

/**
 * RolUsuarioUsuario generated by hbm2java
 */
public class RolUsuarioUsuario implements java.io.Serializable {

	private long id;
	private RolUsuario rolUsuario;
	private Usuario usuario;

	public RolUsuarioUsuario() {
	}

	public RolUsuarioUsuario(long id, RolUsuario rolUsuario, Usuario usuario) {
		this.id = id;
		this.rolUsuario = rolUsuario;
		this.usuario = usuario;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public RolUsuario getRolUsuario() {
		return this.rolUsuario;
	}

	public void setRolUsuario(RolUsuario rolUsuario) {
		this.rolUsuario = rolUsuario;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

}
