package com.example.modelo;

// default package
// Generated 29/09/2014 10:20:51 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * RutaTuristica generated by hbm2java
 */
public class RutaTuristica implements java.io.Serializable {

	private long id;
	private Usuario usuario;
	private String nombre;
	private String descripcion;
	private Integer habilitado;
	private Date fecha;
	private Set comentarioRutaTuristicas = new HashSet(0);
	private Set sitioRutaTuristicas = new HashSet(0);
	private Set calificacionRutaTuristicas = new HashSet(0);
	private Set fotos = new HashSet(0);

	public RutaTuristica() {
	}

	public RutaTuristica(long id, Usuario usuario) {
		this.id = id;
		this.usuario = usuario;
	}

	public RutaTuristica(long id, Usuario usuario, String nombre,
			String descripcion, Integer habilitado, Date fecha,
			Set comentarioRutaTuristicas, Set sitioRutaTuristicas,
			Set calificacionRutaTuristicas, Set fotos) {
		this.id = id;
		this.usuario = usuario;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.habilitado = habilitado;
		this.fecha = fecha;
		this.comentarioRutaTuristicas = comentarioRutaTuristicas;
		this.sitioRutaTuristicas = sitioRutaTuristicas;
		this.calificacionRutaTuristicas = calificacionRutaTuristicas;
		this.fotos = fotos;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Integer getHabilitado() {
		return this.habilitado;
	}

	public void setHabilitado(Integer habilitado) {
		this.habilitado = habilitado;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Set getComentarioRutaTuristicas() {
		return this.comentarioRutaTuristicas;
	}

	public void setComentarioRutaTuristicas(Set comentarioRutaTuristicas) {
		this.comentarioRutaTuristicas = comentarioRutaTuristicas;
	}

	public Set getSitioRutaTuristicas() {
		return this.sitioRutaTuristicas;
	}

	public void setSitioRutaTuristicas(Set sitioRutaTuristicas) {
		this.sitioRutaTuristicas = sitioRutaTuristicas;
	}

	public Set getCalificacionRutaTuristicas() {
		return this.calificacionRutaTuristicas;
	}

	public void setCalificacionRutaTuristicas(Set calificacionRutaTuristicas) {
		this.calificacionRutaTuristicas = calificacionRutaTuristicas;
	}

	public Set getFotos() {
		return this.fotos;
	}

	public void setFotos(Set fotos) {
		this.fotos = fotos;
	}

}
