package com.example.modelo;

// default package
// Generated 29/09/2014 10:20:51 PM by Hibernate Tools 4.0.0

/**
 * SitioRutaTuristica generated by hbm2java
 */
public class SitioRutaTuristica implements java.io.Serializable {

	private long id;
	private RutaTuristica rutaTuristica;
	private Sitio sitio;

	public SitioRutaTuristica() {
	}

	public SitioRutaTuristica(long id, RutaTuristica rutaTuristica, Sitio sitio) {
		this.id = id;
		this.rutaTuristica = rutaTuristica;
		this.sitio = sitio;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public RutaTuristica getRutaTuristica() {
		return this.rutaTuristica;
	}

	public void setRutaTuristica(RutaTuristica rutaTuristica) {
		this.rutaTuristica = rutaTuristica;
	}

	public Sitio getSitio() {
		return this.sitio;
	}

	public void setSitio(Sitio sitio) {
		this.sitio = sitio;
	}

}
