package com.example.modelo;

// default package
// Generated 29/09/2014 10:20:51 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Sitio generated by hbm2java
 */
public class Sitio implements java.io.Serializable {

	private long id;
	private Usuario usuario;
	private String nombre;
	private String direccion;
	private String latitud;
	private String longitud;
	private String descripcion;
	private Integer habilitado;
	private Date fecha;
	private String telefono;
	private Set sitioRutaTuristicas = new HashSet(0);
	private Set checkins = new HashSet(0);
	private Set fotos = new HashSet(0);
	private Set sitioCategoriaSitios = new HashSet(0);
	private Set calificacionSitios = new HashSet(0);
	private Set comentarioSitios = new HashSet(0);
	private Set telefonoSitios = new HashSet(0);
	private Set dias = new HashSet(0);
	private Set promocions = new HashSet(0);

	public Sitio() {
	}

	public Sitio(long id, Usuario usuario) {
		this.id = id;
		this.usuario = usuario;
	}

	public Sitio(long id, Usuario usuario, String nombre, String direccion,
			String latitud, String longitud, String descripcion,
			Integer habilitado, Date fecha, String telefono,
			Set sitioRutaTuristicas, Set checkins, Set fotos,
			Set sitioCategoriaSitios, Set calificacionSitios,
			Set comentarioSitios, Set telefonoSitios, Set dias, Set promocions) {
		this.id = id;
		this.usuario = usuario;
		this.nombre = nombre;
		this.direccion = direccion;
		this.latitud = latitud;
		this.longitud = longitud;
		this.descripcion = descripcion;
		this.habilitado = habilitado;
		this.fecha = fecha;
		this.telefono = telefono;
		this.sitioRutaTuristicas = sitioRutaTuristicas;
		this.checkins = checkins;
		this.fotos = fotos;
		this.sitioCategoriaSitios = sitioCategoriaSitios;
		this.calificacionSitios = calificacionSitios;
		this.comentarioSitios = comentarioSitios;
		this.telefonoSitios = telefonoSitios;
		this.dias = dias;
		this.promocions = promocions;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getLatitud() {
		return this.latitud;
	}

	public void setLatitud(String latitud) {
		this.latitud = latitud;
	}

	public String getLongitud() {
		return this.longitud;
	}

	public void setLongitud(String longitud) {
		this.longitud = longitud;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Integer getHabilitado() {
		return this.habilitado;
	}

	public void setHabilitado(Integer habilitado) {
		this.habilitado = habilitado;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public Set getSitioRutaTuristicas() {
		return this.sitioRutaTuristicas;
	}

	public void setSitioRutaTuristicas(Set sitioRutaTuristicas) {
		this.sitioRutaTuristicas = sitioRutaTuristicas;
	}

	public Set getCheckins() {
		return this.checkins;
	}

	public void setCheckins(Set checkins) {
		this.checkins = checkins;
	}

	public Set getFotos() {
		return this.fotos;
	}

	public void setFotos(Set fotos) {
		this.fotos = fotos;
	}

	public Set getSitioCategoriaSitios() {
		return this.sitioCategoriaSitios;
	}

	public void setSitioCategoriaSitios(Set sitioCategoriaSitios) {
		this.sitioCategoriaSitios = sitioCategoriaSitios;
	}

	public Set getCalificacionSitios() {
		return this.calificacionSitios;
	}

	public void setCalificacionSitios(Set calificacionSitios) {
		this.calificacionSitios = calificacionSitios;
	}

	public Set getComentarioSitios() {
		return this.comentarioSitios;
	}

	public void setComentarioSitios(Set comentarioSitios) {
		this.comentarioSitios = comentarioSitios;
	}

	public Set getTelefonoSitios() {
		return this.telefonoSitios;
	}

	public void setTelefonoSitios(Set telefonoSitios) {
		this.telefonoSitios = telefonoSitios;
	}

	public Set getDias() {
		return this.dias;
	}

	public void setDias(Set dias) {
		this.dias = dias;
	}

	public Set getPromocions() {
		return this.promocions;
	}

	public void setPromocions(Set promocions) {
		this.promocions = promocions;
	}

}
