package com.example.modelo;

// default package
// Generated 29/09/2014 10:20:51 PM by Hibernate Tools 4.0.0

/**
 * SitioCategoriaSitio generated by hbm2java
 */
public class SitioCategoriaSitio implements java.io.Serializable {

	private long id;
	private CategoriaSitio categoriaSitio;
	private Sitio sitio;

	public SitioCategoriaSitio() {
	}

	public SitioCategoriaSitio(long id, CategoriaSitio categoriaSitio,
			Sitio sitio) {
		this.id = id;
		this.categoriaSitio = categoriaSitio;
		this.sitio = sitio;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public CategoriaSitio getCategoriaSitio() {
		return this.categoriaSitio;
	}

	public void setCategoriaSitio(CategoriaSitio categoriaSitio) {
		this.categoriaSitio = categoriaSitio;
	}

	public Sitio getSitio() {
		return this.sitio;
	}

	public void setSitio(Sitio sitio) {
		this.sitio = sitio;
	}

}
