package com.example.modelo;

// default package
// Generated 29/09/2014 10:20:51 PM by Hibernate Tools 4.0.0

/**
 * TelefonoSitio generated by hbm2java
 */
public class TelefonoSitio implements java.io.Serializable {

	private long id;
	private Sitio sitio;
	private String numero;

	public TelefonoSitio() {
	}

	public TelefonoSitio(long id, Sitio sitio) {
		this.id = id;
		this.sitio = sitio;
	}

	public TelefonoSitio(long id, Sitio sitio, String numero) {
		this.id = id;
		this.sitio = sitio;
		this.numero = numero;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Sitio getSitio() {
		return this.sitio;
	}

	public void setSitio(Sitio sitio) {
		this.sitio = sitio;
	}

	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

}
